# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrow',
            new_name='borrower',
        ),
    ]
