# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171202_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set Book as returned'),)},
        ),
    ]
